services:
  mediathek-nas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mediathek-nas
    ports:
      - "8000:8000"
    environment:
      APP_DATA_DIR: /data
      DOWNLOAD_ROOT: /downloads
      TZ: Europe/Berlin
    volumes:
      - ./data:/data
      - ./downloads:/downloads
    restart: unless-stopped
